server:
  port: 8090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    password: postgres
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
          format_sql: true
      show-sql: true
  mq:
    queues:
      order-creation: order-creation
