services:
  rabbitmq:
    image: rabbitmq:3.7.8-management
    container_name: rabbitmq_management
    ports:
     - 5672:5672
     - 15672:15672
    environment:
     - RABBITMQ_DEFAULT_USER=rabbitmq
     - RABBITMQ_DEFAULT_PASS=rabbitmq

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    container_name: grafana
    volumes:
            - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
        - 3000:3000
    networks:
        - monit
  
  prometheus:
    image: prom/prometheus:latest
    user: "root:root"
    container_name: prometheus
    restart: unless-stopped
    volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
    ports:
        - 9090:9090
    networks:
        - monit
  
  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    networks:
      - postgres-compose-network
    
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 15432:80
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
  monit:
    driver: bridge



