global:
    scrape_interval: 15s

scrape_configs:

- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets:
        - prometheus:9090